title: BHF DSC HDS Documentation
description: BHF Data Science Centre Health Data Science Team documentation for CVD-COVID-UK/COVID-IMPACT members.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  BHF DSC GitHub: https://github.com/BHFDSC


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
